---
- name: Updating Jira Issue
  hosts: all
  tasks: 
  - name: Transition Issue to Done
    uri:
      url: https://automation.atlassian.com/pro/hooks/fad90c0e95b2c53dbe3b12b0015878ccd87b8a58
      method: POST
      body_format: json
      body: {"issues": ["VI-2"]}
      headers:
        Content-Type: "application/json"
